"""GENERATED by the model-enablement workflow (cpu-model-wiring skill) — 2026-09-15.

Do not hand-maintain. Regenerate by re-running the workflow on this arch. This is
workflow OUTPUT (a reviewable diff to upstream), not pre-authored per-model support.

Enablement case C (new-kernel leg): DeepSeek-V4 flash (DeepseekV4ForCausalLM).
The MLA core, dense GEMMs, MoE grouped-GEMM, RMSNorm, RoPE and top-k are ALL
covered by existing CPU/AMX kernels inherited from the DeepSeek-V2 CPU path
(coverage-gate report: plugin/coverage/deepseek_v4_flash_coverage.yaml). The ONLY
uncovered work is the DeepSeek Sparse Attention (DSA) "lightning indexer" family:
  1 PARTIAL  dsa_indexer_logits_gemm   (AVX-512 ref exists; AMX M=16 kernel missing)
  3 GAP      kv_compressor, fp8_group_quant+hadamard (indexer query), sparse_prefill
             (CUDA/HIP/Triton only — no CPU path).

This override (a) overrides the built-in ``DeepseekV4ForCausalLM`` by ``__name__``
(registry overwrite=True), carrying the CPU_ENABLEMENT provenance, and (b) installs
CPU *reference* implementations for the DSA GAP ops so the model executes end-to-end
on CPU (make-it-work). The reference ops are correctness-first; the make-it-fast pass
replaces the RoI-ranked hot ones with AMX kernels (see cpu-optimizer / kernel-authoring).
"""

from __future__ import annotations

import logging
from typing import Optional

from intel_cpu_models import _dsv4_cpu_infra
from intel_cpu_models._cpu_enablement import CpuEnablementMixin
from sglang.srt.models.deepseek_v4 import (
    DeepseekV4ForCausalLM as _UpstreamDeepseekV4ForCausalLM,
)

logger = logging.getLogger(__name__)

# Install the CPU DSV4 KV-cache/memory-pool infra patch (make-it-work layer) as soon
# as this model module is imported by the registry.
_dsv4_cpu_infra.install()


class DeepseekV4ForCausalLM(CpuEnablementMixin, _UpstreamDeepseekV4ForCausalLM):
    # Provenance for the certificate: op -> kernel -> donor / status on CPU.
    CPU_ENABLEMENT = {
        # --- COVERED via the DeepSeek-V2 CPU path (existing kernels) ---
        "dense_gemm": {"kernel": "amx_brgemm_bf16/fp8", "donor": "deepseek_v2"},
        "mla_attention_core": {"kernel": "fused_mla_rope_cpu + flash_attn", "donor": "deepseek_v2"},
        "moe_grouped_gemm": {"kernel": "fused_moe_cpu_amx", "donor": "deepseek_v2/qwen2_moe"},
        "rms_norm": {"kernel": "cpu_rms_norm", "donor": "llama/deepseek_v2"},
        "rope": {"kernel": "cpu_rotary", "donor": "llama/deepseek_v2"},
        "topk_selection": {"kernel": "cpu_topk", "donor": "deepseek_v2"},
        # --- DSA new-kernel leg: reference CPU first, AMX after profiling ---
        "dsa_indexer_logits_gemm": {"kernel": "index_gemm_nn (AVX-512 ref) -> AMX(M=16) TODO", "status": "PARTIAL"},
        "kv_compressor": {"kernel": "cpu reference (torch) -> AMX TODO", "status": "GAP"},
        "fp8_group_quant_hadamard": {"kernel": "cpu reference (torch) -> AMX TODO", "status": "GAP"},
        "sparse_prefill_attention": {"kernel": "cpu reference (torch) -> AMX TODO", "status": "GAP"},
    }

    def __init__(
        self,
        config,
        quant_config=None,
        prefix: str = "",
    ) -> None:
        super().__init__(config, quant_config=quant_config, prefix=prefix)
        self._init_cpu_enablement()


EntryClass = [DeepseekV4ForCausalLM]
