"""GENERATED by the model-enablement workflow (cpu-model-wiring skill) — 2026-10-02.

Do not hand-maintain. Regenerate by re-running the workflow on this arch. Workflow
OUTPUT (a reviewable diff to upstream), not pre-authored per-model support.

Enablement case (new-kernel leg): GLM-5.3 Flash (Glm5NextForConditionalGeneration), a
HYBRID model. 11/45 layers are MLA full-attention (+ DSA indexer) and 34/45 are KDA
(Kimi Delta / gated-delta-rule) LINEAR ATTENTION — the sole authoring GAP. MHC
hash-clustering (norm path), MoE grouped-GEMM, dense SwiGLU, RMSNorm, fp8 block-quant
GEMM, and the DSA indexer are all COVERED/REUSE via the DeepSeek-V4 CPU work
(coverage-gate: plugin/coverage/glm_5_3_flash_coverage.yaml). Precision is a single
fp8-e4m3 128x128 block-quant -> bf16 W8A16 bridge.

This override (a) overrides the built-in ``Glm5NextForConditionalGeneration`` by
``__name__`` (registry overwrite=True), carrying CPU_ENABLEMENT provenance, and
(b) installs the CPU KDA linear-attention backend + dual cache via ``_glm5_cpu_infra``
so the KDA layers execute on CPU with the parity-proven recurrence (self-consistency +
GPU-oracle gated: plugin/validate/test_kda_gpu_oracle.py).
"""

from __future__ import annotations

import logging

from intel_cpu_models import _glm5_cpu_infra
from intel_cpu_models._cpu_enablement import CpuEnablementMixin
from sglang.srt.models.glm5_next import (
    Glm5NextForConditionalGeneration as _UpstreamGlm5NextForConditionalGeneration,
)

logger = logging.getLogger(__name__)

# Install the CPU KDA backend (recurrence + dual cache) when this module is imported.
_glm5_cpu_infra.install()


class Glm5NextForConditionalGeneration(
    CpuEnablementMixin, _UpstreamGlm5NextForConditionalGeneration
):
    # Provenance for the certificate: op -> kernel -> donor / status on CPU.
    CPU_ENABLEMENT = {
        # --- COVERED / REUSE via the DeepSeek-V4/V2 CPU path ---
        "dense_gemm": {"kernel": "amx_brgemm_bf16/fp8", "donor": "deepseek_v2"},
        "mla_attention_core": {"kernel": "fused_mla_rope_cpu + flash_attn", "donor": "deepseek_v2/deepseek_v4"},
        "dsa_indexer": {"kernel": "dsa_indexer_cpu + dsa_sparse_attention_cpu", "donor": "deepseek_v4"},
        "moe_grouped_gemm": {"kernel": "fused_moe_cpu_amx (fp8)", "donor": "deepseek_v2/qwen2_moe"},
        "mhc_hash_clustering": {"kernel": "cpu hc_pre/hc_post/sinkhorn", "donor": "deepseek_v4"},
        "rms_norm": {"kernel": "cpu_rms_norm", "donor": "llama/deepseek_v2"},
        "rope": {"kernel": "cpu_rotary", "donor": "llama/deepseek_v2"},
        "topk_selection": {"kernel": "cpu_topk", "donor": "deepseek_v2"},
        # --- KDA linear attention: authored reference-first, CPU recurrence ---
        "kda_linear_attention": {"kernel": "cpu_kda_extend/decode (gated delta-rule + conv1d + gated-norm)", "status": "AUTHORED"},
        "fused_rms_norm_gated": {"kernel": "rms_norm_gated (cpu)", "status": "AUTHORED"},
    }

    def __init__(self, config, quant_config=None, prefix: str = "") -> None:
        super().__init__(config, quant_config=quant_config, prefix=prefix)
        self._init_cpu_enablement()


EntryClass = [Glm5NextForConditionalGeneration]
