"""GENERATED by the model-enablement workflow (cpu-model-wiring skill) — 2026-09-10.

Do not hand-maintain. Regenerate by re-running the workflow on this arch. This is
workflow OUTPUT (a reviewable diff to upstream), not pre-authored per-model support.

Enablement case A: OLMo 2 (dense GQA/MHA + QK-norm + RoPE + SwiGLU + RMSNorm)
already exists in SGLang and uses only standard layers, so every op is covered by
an EXISTING CPU/AMX kernel (see coverage-gate). The generic CPU path does the real
wiring — the unquantized CPU linear method AMX-prepacks weights at load and
``RadixAttention`` dispatches the ``intel_amx`` backend — so this override only
carries the CPU_ENABLEMENT provenance manifest and a load-time prepack check. It
overrides the built-in ``Olmo2ForCausalLM`` by ``__name__`` (registry overwrite=True).
"""

from __future__ import annotations

from typing import Optional

import torch

from intel_cpu_models._cpu_enablement import CpuEnablementMixin
from sglang.srt.models.olmo2 import Olmo2ForCausalLM as _UpstreamOlmo2ForCausalLM


class Olmo2ForCausalLM(CpuEnablementMixin, _UpstreamOlmo2ForCausalLM):
    # Provenance for the certificate: op -> existing kernel -> donor model on CPU.
    CPU_ENABLEMENT = {
        "dense_gemm": {"kernel": "amx_brgemm_bf16_prepacked", "donor": "llama3_8b/qwen25_7b"},
        "gqa_attention": {"kernel": "intel_amx_attention_backend", "donor": "llama3_8b"},
        "rms_norm": {"kernel": "cpu_rms_norm", "donor": "llama3_8b"},
        "qk_norm": {"kernel": "cpu_rms_norm", "donor": "olmo2 (RMSNorm on q,k)"},
        "rope": {"kernel": "cpu_rotary", "donor": "llama3_8b"},
        "swiglu": {"kernel": "cpu_silu_and_mul", "donor": "llama3_8b"},
        "embed_and_head": {"kernel": "vocab_parallel_embedding_prepacked", "donor": "llama3_8b"},
    }

    def __init__(
        self,
        config,
        quant_config=None,
        prefix: str = "",
        alt_stream: Optional[torch.cuda.Stream] = None,
    ):
        super().__init__(
            config, quant_config=quant_config, prefix=prefix, alt_stream=alt_stream
        )
        self._init_cpu_enablement()


EntryClass = Olmo2ForCausalLM
