"""GENERATED by the model-enablement workflow (cpu-model-wiring skill) — 2026-09-10.

Do not hand-maintain. Workflow OUTPUT (a reviewable diff to upstream), not
pre-authored per-model support.

Enablement case A: OLMoE-1B-7B (sparse MoE: top-8 of 64 experts, dense GQA/MHA +
QK-norm + RoPE + SwiGLU + RMSNorm). Every op is covered by an EXISTING CPU/AMX
kernel — the dense linears by the AMX BRGEMM path, the experts by the FusedMoE CPU
grouped-GEMM path (donor: qwen2_moe / deepseek_v2). The generic CPU path does the
prepacking; this override carries the CPU_ENABLEMENT provenance manifest and the
load-time prepack check. Overrides the built-in ``OlmoeForCausalLM`` by ``__name__``.
"""

from __future__ import annotations

from intel_cpu_models._cpu_enablement import CpuEnablementMixin
from sglang.srt.models.olmoe import OlmoeForCausalLM as _UpstreamOlmoeForCausalLM


class OlmoeForCausalLM(CpuEnablementMixin, _UpstreamOlmoeForCausalLM):
    CPU_ENABLEMENT = {
        "dense_gemm": {"kernel": "amx_brgemm_bf16_prepacked", "donor": "llama3_8b/qwen25_7b"},
        "gqa_attention": {"kernel": "intel_amx_attention_backend", "donor": "llama3_8b"},
        "moe_grouped_gemm": {"kernel": "fused_moe_cpu_amx", "donor": "qwen2_moe/deepseek_v2"},
        "rms_norm": {"kernel": "cpu_rms_norm", "donor": "llama3_8b"},
        "qk_norm": {"kernel": "cpu_rms_norm", "donor": "olmoe (RMSNorm on q,k)"},
        "rope": {"kernel": "cpu_rotary", "donor": "llama3_8b"},
        "swiglu": {"kernel": "cpu_silu_and_mul", "donor": "llama3_8b"},
        "embed_and_head": {"kernel": "vocab_parallel_embedding_prepacked", "donor": "llama3_8b"},
    }

    def __init__(self, config, quant_config=None, prefix: str = ""):
        super().__init__(config, quant_config=quant_config, prefix=prefix)
        self._init_cpu_enablement()


EntryClass = OlmoeForCausalLM
