#!/usr/bin/env python3
"""Day-0 platform calibration: probe a node and emit a filled hardware profile.

Run this ON the target node (via srun). It parses lscpu/numactl for [AUTO]
topology + ISA fields, compiles and runs the microbenchmarks in
tools/microbench for the *achievable* AMX compute and memory ceilings, then
writes a hardware profile YAML that the roofline gate and the GEMM skill consume
unchanged. [SPEC] fields (memory MT/s, tile shape) are left as datasheet inputs.

Usage:
  srun --partition=<part> --cpus-per-task=<n> python tools/calibrate.py \
       --out .agents/skills/kernel-optimization/cpu-gemm-amx-bf16/assets/hardware-profiles/<part>.yaml
"""
import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MB = os.path.join(HERE, "microbench")
ISA_FLAGS = ["avx512f", "avx512_bf16", "amx_tile", "amx_bf16", "amx_int8", "amx_fp16"]


def sh(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True).stdout


def lscpu():
    info = {}
    for line in sh("lscpu").splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            info[k.strip()] = v.strip()
    return info


def parse_cache_bytes(s):
    # e.g. "2 MiB (128 instances)" or "480 MiB"
    m = re.search(r"([\d.]+)\s*(KiB|MiB|GiB)", s or "")
    if not m:
        return 0
    v = float(m.group(1))
    return int(v * {"KiB": 1024, "MiB": 1024**2, "GiB": 1024**3}[m.group(2)])


def cache_instances(s):
    m = re.search(r"\((\d+)\s+instances?\)", s or "")
    return int(m.group(1)) if m else 1


def l2_per_core(info, cores_total):
    total = parse_cache_bytes(info.get("L2 cache"))
    inst = cache_instances(info.get("L2 cache")) or cores_total
    return total // inst if inst else total


def socket0_numa_nodes(sockets, numa_nodes):
    per = max(1, numa_nodes // max(1, sockets))
    return ",".join(str(i) for i in range(per)), per


def build_microbench():
    subprocess.run(
        f"gcc -O3 -march=native -mamx-tile -mamx-bf16 -fopenmp "
        f"{MB}/amx_peak.c -o {MB}/amx_peak", shell=True, check=True)
    subprocess.run(
        f"gcc -O3 -march=native -fopenmp {MB}/stream_triad.c -o {MB}/stream_triad",
        shell=True, check=True)


def run_json(cmd):
    out = sh(cmd).strip().splitlines()
    for line in reversed(out):
        line = line.strip()
        if line.startswith("{"):
            return json.loads(line)
    return {}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="-", help="profile path or - for stdout")
    ap.add_argument("--codename", default="<fill from datasheet>")
    args = ap.parse_args()

    info = lscpu()
    sockets = int(info.get("Socket(s)", "1"))
    cps = int(info.get("Core(s) per socket", "1"))
    tpc = int(info.get("Thread(s) per core", "1"))
    numa = int(info.get("NUMA node(s)", "1"))
    cores_total = sockets * cps
    flags = set(info.get("Flags", "").split())
    caps = [f for f in ISA_FLAGS if f in flags]
    max_mhz = float(info.get("CPU max MHz", "0") or 0)

    has_amx = "amx_bf16" in flags and "amx_tile" in flags
    node_list, cores_per_snc = socket0_numa_nodes(sockets, numa)

    single_tf = socket_tf = full_tf = bw = 0.0
    if has_amx:
        build_microbench()
        env = "OMP_PROC_BIND=close OMP_PLACES=cores"
        single = run_json(
            f"{env} OMP_NUM_THREADS=1 numactl --physcpubind=0 --membind=0 {MB}/amx_peak")
        sock = run_json(
            f"{env} OMP_NUM_THREADS={cps} numactl --cpunodebind={node_list} "
            f"--membind={node_list} {MB}/amx_peak")
        full = run_json(f"{env} OMP_NUM_THREADS={cores_total} {MB}/amx_peak")
        stream = run_json(
            f"{env} OMP_NUM_THREADS={cps} numactl --cpunodebind={node_list} "
            f"--membind={node_list} {MB}/stream_triad")
        single_tf = single.get("per_core_tflops", 0.0)
        socket_tf = sock.get("achievable_compute_tflops", 0.0)
        full_tf = full.get("achievable_compute_tflops", 0.0)
        bw = stream.get("achievable_bw_gbs", 0.0)
    else:
        print("WARNING: no AMX BF16 on this node; achievable block left zero",
              file=sys.stderr)

    fpc = 1024  # ISA constant; verified below
    derived_freq = round(socket_tf * 1e12 / (cps * fpc) / 1e9, 3) if socket_tf else 0.0
    verified = ""
    if single_tf and max_mhz:
        implied_fpc = single_tf * 1e12 / (max_mhz * 1e6)
        verified = f"  # microkernel implies ~{implied_fpc:.0f} FLOP/cyc/core @ max turbo"

    prof = f"""# Auto-generated by tools/calibrate.py (Day-0 calibration).
# [SPEC] fields still require datasheet values; everything else is measured.
part: "{info.get('Model name', 'unknown')}"
codename: "{args.codename}"

sockets: {sockets}
cores_per_socket: {cps}
cores_total: {cores_total}
threads_per_core: {tpc}
numa_nodes: {numa}                # nodes_per_socket = {cores_per_snc}-way SNC

capabilities: [{', '.join(caps)}]

amx_bf16_flops_per_cycle_per_core: {fpc}{verified}
amx_int8_ops_per_cycle_per_core: 2048       # [SPEC]
amx_all_core_freq_ghz: {derived_freq}        # derived from microkernel (NOT turbo)
max_turbo_ghz: {round(max_mhz/1000, 2)}

tile_m: 16                                   # [SPEC]
tile_n: 16                                   # [SPEC]
tile_k: 32                                   # [SPEC]
weight_pack_constraints:
  oc_multiple_of: 16
  ic_multiple_of: 32

l2_bytes_per_core: {l2_per_core(info, cores_total)}
l3_bytes_total: {parse_cache_bytes(info.get('L3 cache'))}

mem_type: "<DDR5/MRDIMM>"                     # [SPEC]
mem_speed_mts: 0                             # [SPEC] datasheet
mem_channels_per_socket: 0                   # [SPEC] datasheet
mem_bytes_per_transfer: 8

achievable:
  estimated: false
  measured_by: "tools/microbench (amx_peak.c, stream_triad.c)"
  single_core_bf16_tflops: {round(single_tf, 3)}
  bf16_compute_tflops_per_socket: {round(socket_tf, 1)}
  bf16_compute_tflops_full_node: {round(full_tf, 1)}
  mem_bw_gbs_per_socket: {round(bw, 1)}
"""
    if args.out == "-":
        sys.stdout.write(prof)
    else:
        with open(args.out, "w") as f:
            f.write(prof)
        print(f"wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
